// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import ScrollIntoViewController from "./scroll_into_view_controller"
application.register("scroll-into-view", ScrollIntoViewController)

import TtsController from "./tts_controller"
application.register("tts", TtsController)

import GlobalTtsController from "./global_tts_controller"
application.register("global-tts", GlobalTtsController)

import TtsToggleController from "./tts_toggle_controller"
application.register("tts-toggle", TtsToggleController)

import LoadingController from "./loading_controller"
application.register("loading", LoadingController)
